#!/bin/bash

printf " \n"
printf " __________ \n"
printf "< compiled >\n"
printf " ---------- \n"
printf "  \                              _\n"
printf "   \                            | |\n"
printf "    \                           | |\n"
printf "     \                          | |\n"
printf "      \    |\\                   | |\n"
printf "       \  /, ~\\                / /\n"
printf "         X     \`-.....-------./ /\n"
printf "          ~-. ~  ~              |\n"
printf "             \             /    |\n"
printf "              \  /_     ___\\   /\n"
printf "              | /\\ ~~~~~   \ |\n"
printf "              | | \\        || |\n"
printf "              | |\\ \\       || )\n"
printf "             (_/ (_/      ((_//\n"